### ISSUE TITLE
PostgreSQL log mount makes log directory unwritable by Rails

### ISSUE THREAD

**Issue by jasonswett** [Ruby-Starter-Kits/Docker-Rails-Generator#49]
First of all, thanks for this great project. Super helpful.

I want to let you know that I found a potential issue.

On [this line](https://github.com/Ruby-Starter-Kits/Docker-Rails-Generator/blob/master/App-Template/docker-compose.yml#L42), it seems to be mounting the PostgreSQL log to the Rails application's `log` directory. This is a problem as it makes the Rails log unwritable by Rails.

I was able to "fix" the problem by commenting out the line. If I'm not mistaken, maybe `./log` could be changed to some other directory as to remove the conflict.

**Comment by MikeRogers0** [comment]
Thank you for the heads up @jasonswett :) I'm going to change the folder to `./log/postgres`, I think that should solve it :)
